name: e_shop
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.4.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  http: ^1.2.1
  connectivity_plus: ^6.0.3
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1
  injectable: ^2.4.2
  get_it: ^7.7.0
  path_provider: ^2.1.3
  hive: ^2.2.3
  go_router: ^14.1.4
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.10+1
  forge_annotation: ^0.0.1
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  injectable_generator: ^2.6.1
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.5.0+1
flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
flutter_gen:
  output: lib/core/gen/
  line_length: 80
  integrations:
    flutter_svg: true
